### ISSUE TITLE
Async Hibike Crash

### ISSUE THREAD

**Issue by jonathan-j-lee** [pioneers/PieCentral#660]
```
('****************** RUNTIME DEBUG ******************',)
('Starting studentCode attempt: 0',)
BAD_EVENTS.HIBIKE_NONEXISTENT_DEVICE
('47251730314250538435293',)
Task exception was never retrieved
future: <Task finished coro=<SmartSensorProtocol.register_sensor() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:144> exception=AttributeError("'NoneType' object has no attribute 'call_soon'")>
Traceback (most recent call last):
  File "/home/fabric/PieCentral/hibike/hibike_process.py", line 152, in register_sensor
    self.quit()
  File "/home/fabric/PieCentral/hibike/hibike_process.py", line 221, in quit
    self.transport.abort()
  File "/home/fabric/.local/share/virtualenvs/runtime-D_WL9N5y/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 186, in abort
    self._abort(None)
  File "/home/fabric/.local/share/virtualenvs/runtime-D_WL9N5y/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 378, in _abort
    self._loop.call_soon(self._call_connection_lost, exc)
AttributeError: 'NoneType' object has no attribute 'call_soon'
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.send_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:160> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.recv_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:187> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.send_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:160> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.recv_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:187> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.send_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:160> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.recv_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:187> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.send_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:160> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.recv_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:187> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.send_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:160> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.recv_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:187> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.send_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:160> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.recv_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:187> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.send_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:160> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<SmartSensorProtocol.recv_messages() done, defined at /home/fabric/PieCentral/hibike/hibike_process.py:187> wait_for=<Future cancelled>>
```
Ran on Python 3.7.2 with Raspberry Pi 3 and four Smart Sensors on one hub. Not sure what's going on here, at the moment.

Edit: Probably occurred because some of the sensors were not flashed. My guess is that a timeout of some sort was triggered.

**Comment by baby-bell** [comment]
Sensor detection hasn't been well tested, so this seems likely.
